### PR TITLE
fix: added check that no enum types are deleted

### LINKED ISSUE #569: address enum fails to update
### Version information
- **terraform**: _Please specify the version of Terraform you are using._
`terraform_version: 1.5.7`

- **terraform provider**: _Please specify the version of the provider you are using._

`commercetools: 1.11.2`

### Describe the bug

Removing an item from an enum in a type results in an error
```
│ Error: The given keys must be equal to the existing enum keys.
│ 
│   with module.commercetools-config-sdmy.commercetools_type.delivery_manager_address,
│   on .terraform/modules/commercetools-config-sdmy/address.tf line 1, in resource "commercetools_type" "delivery_manager_address":
│    1: resource "commercetools_type" "delivery_manager_address" {
```

While the plan output showed it wanting to remove the item (also note the ordering):

```
 # module.commercetools-config-sdmy.commercetools_type.delivery_manager_address will be updated in-place
  ~ resource "commercetools_type" "delivery_manager_address" {
        id                = "46deb58a-b08a-4edc-8c86-9df51054580e"
        name              = {
            "en" = "Custom Address with Delivery Manager attributes"
        }
        # (4 unchanged attributes hidden)

      ~ field {
            name       = "carrierCode"
            # (3 unchanged attributes hidden)

          ~ type {
                name = "Enum"

              ~ value {
                  ~ key   = "TODO" -> "DPD"
                  ~ label = "To Do" -> "Express delivery by Dynamic Parcel Distribution"
                }
              ~ value {
                  ~ key   = "DPD" -> "HERMESPOS"
                  ~ label = "Express delivery by Dynamic Parcel Distribution" -> "Express delivery by Hermes"
                }
              ~ value {
                  ~ key   = "HERMESPOS" -> "DHL"
                  ~ label = "Express delivery by Hermes" -> "Express delivery by DHL"
                }
              ~ value {
                  ~ key   = "DHL" -> "EVRI"
                  ~ label = "Express delivery by DHL" -> "Express delivery by Evri"
                }
              ~ value {
                  ~ key   = "EVRI" -> "YODEL"
                  ~ label = "Express delivery by Evri" -> "Express delivery by Yodel"
                }
              - value {
                  - key   = "YODEL" -> null
                  - label = "Express delivery by Yodel" -> null
                }
            }
        }

        # (2 unchanged blocks hidden)
    }
```

### To Reproduce
Steps to reproduce the behavior.

Have a commercetools type defined for address

```
resource "commercetools_type" "delivery_manager_address" {
  key = "delivery-manager-address"
  name = {
    en = "Custom Address with Delivery Manager attributes"
  }
  resource_type_ids = ["address"]
 
  field {
    name = "carrierCode"
    label = {
      en = "Carrier Code"
    }

    type {
      name = "Enum"
      value {
        key   = "TODO"
        label = "To Do"
      }
      value {
        key   = "foo"
        label = "foo delivery"
      }
      value {
        key   = "bar"
        label = "bar delivery"
      }
    }
  }
```

then try to remove the `TODO` item

### Expected behavior
The enum should be updated to only contain the `foo` and `bar` carrierCodes

### Additional context

https://github.com/frasers-group/ec-fx-mach-config/actions/runs/13414512251/job/37472017464 -- the failing run

https://github.com/frasers-group/ec-fx-components/pull/5599 -- the code

### PR DESCRIPTION
**Pull request by demeyerthom**
Fixes #569

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

 

-  Throw error when deleting an enum type. This still allows for renaming enum types, it only checks if the total number of new values is smaller than old values

### CODE REVIEW

File: commercetools/resource_type.go [hunk 1]
```diff
@@ -785,6 +785,10 @@ func updateCustomFieldEnumType(fieldName string, old, new platform.CustomFieldEn
 		newValues.Set(new.Values[i].Key, new.Values[i])
 	}
 
+	if newValues.Len() < oldValues.Len() {
```
Comment (webwiebe) [inline commercetools/resource_type.go:788]: This is indeed a better error message but it won't catch my initial case where I removed the todo item from the list and added a couple of new values. 

```if 5 < 3 {```

Comment (demeyerthom) [reply commercetools/resource_type.go:788]: Gah, I guess we need to check for keys specifically then. Will update

**Review by webwiebe — APPROVED** [review]
